build:
  phpunit:
    image: daothaison/ci-workspace:0.0.2
    commands:
    - echo sleep1
    - framgia-ci run
    - echo sleep2
    - echo sleep3
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
deploy:
  docker:
    username: octocat
    password: password
    email: xdangminhtruongx@gmail.com
    repo: dangminhtruong/Havana_Laravel
project_type: php
test:
  eslint:
    ignore: false
    command: eslint --format=checkstyle
      --output-file=.framgia-ci-reports/eslint.xml
      resources/assets/js/ --ext .js
  phpunit:
    ignore: false
    command:
      - php -dzend_extension=xdebug.so vendor/bin/phpunit
        --coverage-clover=.framgia-ci-reports/coverage-clover.xml
        --coverage-html=.framgia-ci-reports/coverage
